name: detectree
channels:
  - conda-forge
dependencies:
  - click
  - contextily
  - descartes
  - detectree
  - geopandas
  - laspy<2.0.0
  - lastools
  - laszip
  - matplotlib
  - numpy
  - osmnx>=0.15
  - python-slugify
  - pip
  - pip:
    - -e .
  - rasterio
  - shapely
