name: detectree
channels:
  - conda-forge
dependencies:
  - click
  - contextily
  - descartes
  - detectree
  - geopandas
  - matplotlib
  - numpy
  - osmnx>=0.15
  - python-slugify
  - pip
  - pip:
    - -e .
    - laspy[laszip]>=2
  - rasterio
  - shapely
